language: java
jdk:
  - openjdk8
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
  - unzip -qq gradle-6.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.8
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
script:
  - gradle test build